apiVersion: apps/v1
kind: Deployment

metadata:
  name: employee1-api

spec:
  replicas: 2

  selector:
    matchLabels:
      app: employee1-api

  template:
    metadata:
      labels:
        app: employee1-api

    spec:
      containers:
      - name: employee1-api
        image: employee1-api:latest
        ports:
        - containerPort: 8081